// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzHyvO-MfKImQnE6cGz2bAZxx40EG5L3s',
    appId: '1:564366639477:web:1df32dea3b1f211035533c',
    messagingSenderId: '564366639477',
    projectId: 'daymondcollaboration',
    authDomain: 'daymondcollaboration.firebaseapp.com',
    storageBucket: 'daymondcollaboration.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5GDwKMwKVjnz0PcbM5iAIFKUNAZGz7jU',
    appId: '1:564366639477:android:7f122e005a90d7ae35533c',
    messagingSenderId: '564366639477',
    projectId: 'daymondcollaboration',
    storageBucket: 'daymondcollaboration.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3zsvWfuwTtR0ornYErFVMiuRF2gXoAP8',
    appId: '1:564366639477:ios:1fba300dfdf34a4035533c',
    messagingSenderId: '564366639477',
    projectId: 'daymondcollaboration',
    storageBucket: 'daymondcollaboration.firebasestorage.app',
    iosBundleId: 'com.distribution.daymond',
  );
}
